# Generated by Django 4.2.11 on 2024-05-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0005_alter_customuser_id_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
