# Generated by Django 4.2.11 on 2024-05-29 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0007_alter_review_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
