# Generated by Django 4.2.11 on 2024-06-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0011_favarit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favarit',
            name='update_datetime',
        ),
    ]
